services:
  - type: web
    name: url-shortener-backend
    env: node
    rootDir: backend
    buildCommand: yarn install && npx prisma generate && yarn build
    startCommand: npx prisma migrate deploy && yarn start:prod
    healthCheckPath: /shortener/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener-db
          property: connectionString

databases:
  - name: url-shortener-db
    databaseName: url_shortener
    user: url_shortener_user