services:
  - type: web
    name: url-shortener-backend
    env: node
    buildCommand: yarn install && yarn build && npx prisma generate
    startCommand: yarn start:prod
    healthCheckPath: /shortener/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener-db
          property: connectionString

databases:
  - name: url-shortener-db
    databaseName: url_shortener
    user: url_shortener_user
